build:
  commands:
    - sudo apt-get update
    - sudo apt-get install -y openjdk-11-jdk
services:
  - type: web
    name: my-app
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: JAVA_HOME
        value: /usr/lib/jvm/java-11-openjdk-amd64
