build:
  commands:
    - echo "Building the Docker image..."

services:
  - type: web
    name: SOA2XLS_Turnover
    env: docker  # Change to docker since you're using a Dockerfile
    dockerfilePath: ./Dockerfile
    autoDeploy: trueregion: oregon  # Use your preferred region
    plan: free
    docker:
      dockerfilePath: Dockerfile  # Ensure this points to your Dockerfile
  buildCommand: |
      echo "Building the Docker image..."
  startCommand: |
      export JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64
      export PATH=$JAVA_HOME/bin:$PATH
      gunicorn app:app
