build:
  commands:
    - sudo apt-get update
    - sudo apt-get install -y openjdk-11-jdk
services:
  - type: web
    name: my-flask-app
    env: python
    pythonVersion: 3.9
    buildCommand: |
      apt-get update && \
      apt-get install -y openjdk-11-jdk && \
      export JAVA_HOME=$(dirname $(dirname $(readlink -f $(which java)))) && \
      pip install -r requirements.txt
    startCommand: gunicorn app:app
