build:
  commands:
    - sudo apt-get update
    - sudo apt-get install -y openjdk-11-jdk
services:
  - type: web
    name: SOA2XLS_Turnover
    env: python
    region: oregon  # Use your preferred region
    plan: free
    buildCommand: |
      apt-get update && \
      apt-get install -y build-essential libssl-dev libffi-dev openjdk-11-jdk && \
      export JAVA_HOME=$(dirname $(dirname $(readlink -f $(which java)))) && \
      python -m pip install --upgrade pip && \
      python -m pip install -r requirements.txt
    startCommand: gunicorn app:app
    pythonVersion: 3.10  # Change to Python 3.10 or 3.9
    envVars:
      - key: JAVA_HOME
        value: /usr/lib/jvm/java-11-openjdk-amd64
      - key: PATH
        value: $JAVA_HOME/bin:$PATH
